### ISSUE TITLE
[Bug] Removing default mob spawns from essence list doesn't work

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#11]
I removed Endermites from the list of essences dropping from ender bones entirely and they still drop. I tried both setting the drop weight to 0.0 and removing the entire entry for them without any luck. I haven't tested, but I also tried to disable Silverfish essence in the same manner.

**Comment by Yuudaari** [comment]
Well that’s weird. I’ll test, thanks

**Comment by Yuudaari** [comment]
Hmm, this works for me. To reaffirm, you're removing the entire endermite entry, correct? They will still drop from bones if you are just removing the "bones" section of their config, because that section has to exist, so it'll add it if it doesn't have it.

That means removing this entire thing:
![image](https://user-images.githubusercontent.com/6081834/34329067-fdbede08-e8b7-11e7-97b8-70e8aff513f6.png)

**Comment by Yuudaari** [comment]
Setting it to 0.0 drop_weight also works for me. Can you gist or pastebin your config file?

**Comment by Dragnier** [comment]
Here is a gist: https://gist.github.com/Dragnier/9c0af1d27453479d3fbc5503ee89feee

Everything there as far as the bone drops is what was default other than adding cyberware:cyberzombie, changing a few drops weights, and removing Endermites and Silverfish.

**Comment by Yuudaari** [comment]
https://gist.github.com/Dragnier/9c0af1d27453479d3fbc5503ee89feee#file-soulus-json-L351
Missing a comma.

I'm surprised this didn't regenerate your config file. Make sure you make backups before you make changes, because at the moment config files that error are usually regenerated from the defaults.

**Comment by Dragnier** [comment]
Ah, not sure how I missed that to be honest, but hit happens to everyone. Thanks for the help! I'll close this and fix the error. Also, I always backup configs out of habit when working on suff.

**Comment by Yuudaari** [comment]
Glad it's fixed! Happy to help =)
