### ISSUE TITLE
Solous Bones not dropping from anything please help.

### ISSUE THREAD

**Issue by DrakeAedus1** [Yuudaari/soulus#118]

**Comment by Yuudaari** [comment]
Sorry, I can't know what your issue is with so little information. Are you playing in a modpack? Have you just installed Soulus on its own? Are the creatures summoned or natural spawns? If they're natural-spawned creatures, is your `creatures.json` config set to allow natural-spawned creatures to drop items? Because by default, Soulus bones will only drop from summoned creatures.

**Comment by DrakeAedus1** [comment]
> Sorry, I can't know what your issue is with so little information. Are you playing in a modpack? Have you just installed Soulus on its own? Are the creatures summoned or natural spawns? If they're natural-spawned creatures, is your `creatures.json` config set to allow natural-spawned creatures to drop items? Because by default, Soulus bones will only drop from summoned creatures.

Yes i am playing a modpack. It is "Mystical Skies". No Solous is not the only mod. Naturally spawned creatures AND Summoner spawner creature are not dropping bones. How do i access the Creatures.json

**Comment by Yuudaari** [comment]
Make an issue on the Mystical Skies repo: https://github.com/NFINIT-Development/mystical-skies/issues
Or ask on their CurseForge page:
https://www.curseforge.com/minecraft/modpacks/mystical-skies
Or join their Discord:
https://discord.gg/bC3Wga5

I don’t have time to figure out why things work a certain way in a modpack, as it’s likely set up that way intentionally by the modpack creator. They should be able to tell you how you’re meant to get the bones. Thanks!
