### ISSUE TITLE
Late-game summoner upgrades for activation when there are no nearby players

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#13]
Hi, I saw your mod and thought it was a great way to progressively add upgrades to a spawner system, versus the traditional soul shards or powered spawner methods. The various upgrades really give it a feel as if you're building something substantial - however I saw that the Murky Orb only increase the range by 1 block, in some late game packs that need heavy duty spawners - they prefer to build that mob farm far away, preferably in a void dimension, to avoid the entity lag. 

Is there a way to possibly have it configured so that after a certain amount of upgrades, a spawner will always continue to work regardless where the player is located?

Thanks again!

**Comment by Yuudaari** [comment]
A similar thing is on my future todo, to create some kind of "totem" from an amalgamation of drops of all kinds of creatures which will function as a "player" to a summoner. (eg, the more of these things close to the summoner, the faster it will spawn). That's likely what I'll go with instead of making murky orb suddenly become overpowered. Thanks for the suggestion tho!

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Soul Totem](https://trello.com/c/5RAEnxeC/96-soul-totem)

**Comment by Vyraal1** [comment]
Great! The soul totem is a much better implementation than the Murky Orbs idea, I like it that better.

**Comment by Yuudaari** [comment]
Fixed as of [v3.0.0](https://github.com/Yuudaari/soulus/releases/tag/v3.0.0)

Hehe, forgot to close...
