### ISSUE TITLE
[Issue] Massive Issue with Natural Spawning

### ISSUE THREAD

**Issue by accessdenied0** [Yuudaari/soulus#16]
Hello @Yuudaari 

**Issue:** No natural Spawning from any mobs and unable to spawn any kind of hostiles
**Forge:** 14.23.1.2571
**Mod Version:** Soulus-1.12.2-1.5.0 (-641183f)
**Description:**
I ran into the problem that Soulus made it impossible to gain any Mob-resources. Any kind of Mob doesn't spawn naturally and get "wiped" soon I load a world. In addition any kind of Hostiles aren't able to spawn. With command "summon" for example it just put the message "Unable to Summon". 
I didn't post any logs here because, there was nothing out of the unusual. I just found out the cause of this issue by removing mods one by one.
So far I can't tell if it is a compat issue or something else. 
I tried deleting the soulus.json config didn't help.

I hope you can help me here.

access_denied

**Comment by Yuudaari** [comment]
See the [Creatures Config](https://github.com/Yuudaari/soulus/blob/master/docs/CONFIG.md#config-creatures-)

All spawning is disabled by default. You must enable it via the config.

**Comment by accessdenied0** [comment]
`[...]"glue": {
		"food_amount": 1,
		"food_saturation": 0.0,
		"food_duration": 32,
		"food_quantity": 1,
		"food_always_edible": true,
		"food_effects": [
			{
				"effect": "nausea",
				"duration": 200
			}
		]
	},
	"creatures": {
		"*": {
			"*": {
				"*": {
					"spawn_chance": 1.0,
					"has_drops": true
				}
			}
		}
	},
	"murky_orb": {
		"required_essence": 64
	},[...]`

sorry but... this is very unconventional or... "awkward" in middle of this mess of code is a so important config hidden? Further more... even if it is a skyblock map or so, who likes to disable all mobs per default?
Maybe warn people on the front page or at least make it optional instead of forcing.
Well it is just my opinion... because I do no really like this inconvenience...
besides that it is a very useful, powerful and cool function.

**Comment by Yuudaari** [comment]
Due to the nature of JSON, I can't choose the way it's sorted. 

The whole point of this mod is to disable spawns so that spawning boxes are useless, and to instead add life back to the world through a long process of continual improvement. And yes, mob spawning being disabled by default is the very first thing mentioned in the [README](https://github.com/Yuudaari/soulus#no-mob-spawning-) of the mod, and it also links to the creature config.

The config file makes everything in the mod configurable, that's why there's so much. I could split it up into multiple configs, and I might do that eventually, but it's not really a priority.

Changing this config isn't especially hard if you're using an actual code editor. I highly recommend *not* using notepad, if that's what you're doing. However, even if you are, even notepad has a way to find a string of text, just search for `"creatures":` and you'll find the config.

**Comment by accessdenied0** [comment]
Isn't it a bit of an conundrum? You need Enderpearls and Bones to make these spawners and ANY other spawner (including modded) stops working? Does your spawner work then, if even Minecraft itself is unable to spawn? Did I miss something in between?
I mean I get it, with Ex-Nihilo you can obtain called items, but still...

To the Readme: it is nice. But not everyone take a risk to look up such an important thing to search through it. Well I should, that is no doubt. [But still... ](https://en.wikipedia.org/wiki/Luser)

Well at least you took the time to explain.

**Comment by Yuudaari** [comment]
In a normal world fossils are added to the world so you can get bone chunks and make a summoner, and in a skyblock world, there is Ex Nihilo Creatio support, so you can get bone chunks and make a summoner. The summoner-summoned mobs are exempted from no-mob-spawning, there is no way to stop those from being summoned.

**Comment by accessdenied0** [comment]
ah ok. That makes more sense now. Thank you :)

**Comment by Yuudaari** [comment]
No problem! Thanks for your interest in the mod. Sorry it's been so confusing to configure. If you have any suggestions of ways to make it easier to pick up, let me know.
