### ISSUE TITLE
Localisation name for custom mobs

### ISSUE THREAD

**Issue by Thyriel** [Yuudaari/soulus#23]
Only a minor issue: When adding totally new entry to essences.json there seems to be no way to specify a localisation name so essence / book is then shown ingame as item.soulus:essence/soulbook.mobID.name

Spawning / obtaining these essences works great, even the spawner has the correct mob rendering in it but would be great if i could specify a name in essences.json to be used.

**Comment by Yuudaari** [comment]
I didn't think I could actually do this, which is why it works the way it does now, but I'll give this another shot. Originally I would recommend adding extra language to your pack, but if I can figure it out that won't be necessary anymore.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Added automatic name support for essences, soulbooks, and summoners. Added config support for manually naming essences.](https://trello.com/c/MwggobXE/172-added-automatic-name-support-for-essences-soulbooks-and-summoners-added-config-support-for-manually-naming-essences)

**Comment by Yuudaari** [comment]
Fixed as of [v2.5.0](https://github.com/Yuudaari/soulus/releases/tag/v2.5.0)

**Comment by Thyriel** [comment]
Thanks :)
Could you give me a config example of how to use this ?
"Added config support for manually naming essence types."

**Comment by Yuudaari** [comment]
It *should* just work for all mobs automatically (it uses the display name of the mob). If a mob doesn't work, can you let me know which it is? I'll try and fix it. Until then, as soon as you launch the game it should actually fix the current `essences.json`, with a new `name` property in each entry set to `null`. Just change that to whatever you want the name to be, it will name the items of that type `<name> Essence`, `Soulbook of <name>`, and `Summoner of <name>`

**Comment by Thyriel** [comment]
Works like a charm :) All are automatically named now correctly based on the mobs name and manually renaming them works too.
Interestingly the newly generated essences.json also reordered most "spawns" and "loot" sections for some reason but that shouldn't make any difference

**Comment by Yuudaari** [comment]
Yea, the order of a JSON object is never guaranteed. Basically, what happens there is the original data is imported into the game, it uses the default values for anything missing, and then it creates a new JSON file from it. If the two files don't have the same data (in this case, they don't, since `name` was added), and the file text is different (obviously), the original file is replaced with the new one. Therefore, if your file is correct and has a different order, it will still keep it (since the content of the JSON objects are the same). If it always replaced the file if just the text was different it would probably replace all the files with a new one every time it loaded, as all the orders of the JSON objects would be randomised.

**Comment by Yuudaari** [comment]
I'm not sure if you know (I don't remember if I mentioned it in the readme anywhere) but you can actually use `/soulus reload` to reload all the configs while in game. When adding or removing stuff to soulus such as essences this will likely be your best friend.
