### ISSUE TITLE
Feedback & Minor Suggestions

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#24]
**Ash** - What type of plants does it work on? Does it work on any block that extends blockBush (eg, which would make it workable with all of the plants from Plants mod and gardens from Pam's Harvestcraft)? Also the block itself doesn't have a localized name I think.
![image](https://user-images.githubusercontent.com/26587049/35490835-61749892-0470-11e8-840c-5c3d4603f551.png)

**Bark** - maybe instead of the random chance of breaking a log to get Bark, maybe breaking it with a Sledgehammer results in Bark 100% of the time?

**Configs - Spawners** - Just to confirm, just leaving one pair empty brackets for `summoner_replacement.json
` is enough to make sure all spawners work normally? I'm using a combination of Quark dungeons and Doomlike Dungeons (Although I don't think the latter is detected by your mod) and I need the spawners there to increase the danger.

**Configs - Worldgen** - Can there be a global configs to turn off worldgen (fossils, and summoners replacing spawners)? It'll make it easier for pack makers to be able to handle the worldgen with other dedicated mods like CofhWorld or MMD Orespawn

**Composer** - I just saw the Composer - big fan of that multiblock, I don't think there's another crafting mechanic like it so far. Would it be possible to add Zenscript support for this one actually?

**JEI Tooltips** - Thanks for these, always like it when mods add their own JEI tabs.

**Soul Totem** - Does this only work as a fake player for your spawners? What about vanilla spawners found in-world (assuming they are enabled)?

Not sure if you just wanted to copy and paste this in your FAQ but this is essentially what I did to re-enable the mob spawns back again since I see people asking:

```
{
	"*": {
		"*": {
			"*": {
				"spawn_chance": 1.0,
				"drops": {
                                                "has_xp": true,
						"all": {
							"whitelisted_drops": [
								"*"
							],
							"blacklisted_drops": []
						}
				}
			}
		}
	}
}
```

**Comment by Yuudaari** [comment]
Ash: what mod are you using to view this tooltip? I have only explicitly added support for Waila, which uses a different way to render the ash (hence not needing that translation). Is anything else wrong with that tooltip (eg: do I need to support more there). The waila support for Soulus is quite complex and informative, to the point where the mod is not very usable without it. That’s what I’m more worried about than this missing translation. 
As for the plants that it works on, it’s actually kinda a complicated check... I think it uses any block that is “IGrowable” and not double tall, there might be a check for BlockBush in there, but I’m not sure. I’ll test with the mods you mentioned to see when I get a chance.

Bark: I really hate the way that bark works right now, but I haven’t come up with a solution I like yet. I actually don’t like the sledgehammer either (mods add so very many tools already). At some point I’ll figure out a solution to both of these issues (hopefully they’ll work in a similar way). Feel free to send other suggestions about this, if you think of any.

Spawner configs: Actually last update I thought this worked but it actually didn’t. I believe it works for real as of 3.0. That should have been a change in the change log...

Generation config switch: Global config switches (or something like that) is planned. Mainly because of the frequency of creature config requests. 

Zenscript support for the composer is on my todo (probably next update). At the moment if you’re able to add in recipes using the vanilla system (recipe json files... tbh I have no idea if that’s a thing you can do in a pack), you can do it that way, as they support those. But yea, will add in zs support regardless.

Soul Totem: This structure actually serves a dual purpose: Its a chunk loader (9 chunks around block) and a “player” for a summoner when powered. These are the only two uses of it at the moment (no fake player)

As for that config: Actually I recommend clearing that config and letting it regenerate, and then doing the same changes to the new one (setting spawn chance to 1.0). The default config will actually disable vanilla bone drops for the skeletons (which is important because soulus drops custom bones for all of them, and now the majority of them are usable as vanilla bones). Anyway, this complexity is another reason for the global config switches.

The main plan for the mod now that all the main features are complete is to pass through the code and the UX and make sure everything is as nice as it can be. I’ve been in a feature rush the past month and now I have to cleanup the great big mess I made. You can expect the next update to take care of most of these issues, I hope.

Let me know if I missed anything in your post. I’m on vacation right now (till tomorrow night). Typed this whole reply on my phone...

**Comment by Yuudaari** [comment]
Fixed the issue with the ash block, added CraftTweaker support for the Composer, config profiles are now supported (so disabling summoner replacement is more self-explanatory), bark is a future todo, and the rest of these are questions. Closing for these reasons. Feel free to make a new issue or leave a comment if I missed anything.
