### ISSUE TITLE
Animal breeding

### ISSUE THREAD

**Issue by Thyriel** [Yuudaari/soulus#27]
If it is possible, how would i need to configure creatures.json so animals can't spawn (as they do not by default) but still can breed ?
It seems currently when they breed the xp is given, the timer starts until they can breed again but no baby spawns

**Comment by Yuudaari** [comment]
When I first implemented this it was something I didn't think about, but after considering it I decided that it was better this way: the point is to improve your spawner, not spawn a couple things and breed them up. Therefore, it is intentional for this to work this way. Consider it that you're spawning infertile mobs.

I'm not sure there *is* a way for me to support this (via config), I haven't looked yet. I don't know if there's an event for breeding. If there's not, there's nothing I can do, and this is just how it will always work: if you have natural creatures off, breeding is also off.

**Comment by Yuudaari** [comment]
Fixed as of [v3.4.0](https://github.com/Yuudaari/soulus/releases/tag/v3.4.0)
