### ISSUE TITLE
lag on machines

### ISSUE THREAD

**Issue by Zygus42** [Yuudaari/soulus#39]
Soulus-1.12.2-3.3.0-739ccb0
forge-1.12.2-14.23.1.2607-installer-win

Noticing some lag on some of your machines when they're just sitting in the world not doing anything, such as the Composer and the Soul Totem.  Recommend the use of the LagGoggles mod to have a look at your machines and see if you can figure out what's happening and try to reduce the lag.

**Comment by Yuudaari** [comment]
It's likely because of my structure code, I haven't looked into optimising it yet. Is it just those two machines that cause the lag?

**Comment by Zygus42** [comment]
Sorry, didn't do any extensive testing, just plonked a couple of machines down and had a look with LagGoggles.  It's always possible that if the machines are in a proper setup they would produce different lag as well.  A good example of this is the vanilla Hopper, which produces ludicrous lag if it has contents and the container it's going into is full, but if you just put it on the ground or in other kind of setup is fine.  If you have a test setup for your mod, just add LagGoggles mod to it and have a look.

**Comment by Yuudaari** [comment]
Yea, I did end up testing and rewriting most of the update code for all my mod's tile entities. There's more improvements to be made but as is it's about a 80% reduction in disabled/invalid/nonfunctioning machines, and about a 30% (avg) in functioning ones (Summoner, Soul Totem, Composer). The Composer is still much slower than I'd like it to be, but it does do complex things so it's kinda to be expected. I'll look into improving that again later... I think the improvements as is are good enough to last through the rest of the big mod features. (After that point I'll be rewriting the whole mod, one file at a time, in order to improve efficiency and readability)

**Comment by Yuudaari** [comment]
Fixed as of [v3.3.1](https://github.com/Yuudaari/soulus/releases/tag/v3.3.1)

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved performance of tile entities](https://trello.com/c/9KPdOlyc/226-improved-performance-of-tile-entities)
