### ISSUE TITLE
Allow mobs to be spawned using eggs or morbs

### ISSUE THREAD

**Issue by YaibaToKen** [Yuudaari/soulus#44]
Is it possible to allow mobs to be spawned using eggs or morbs (item with pokéball like mechanism, added by Thermal Expansion)?

**Comment by Yuudaari** [comment]
Unfortunately there is no event fired by spawn eggs, so I have no way to tell that they were spawned by an egg. There is a potential solution that I thought of a while ago but I'm not sure if it would work and it would take a lot of effort. (Especially for other mods that add their own things like morbs, safari nets, soul vials, as each of these would likely take their own implementation). This is worth doing for sure, but may be implemented far into the future.

**Comment by YaibaToKen** [comment]
Any chance the good folks from the forge development team could add an event fired for spawn eggs? If so, I might just ask them for that xD

**Comment by Yuudaari** [comment]
Usually if you want something in forge you have to write a PR yourself, I just don't have that kind of time right now. I have a solution for the spawn eggs, but it won't work for other mods, and it's not high on my todo — I don't have a lot of free time right now. Atm all I can really do for my mods is bugfixes

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [You can now whitelist items for spawning creatures. By default, spawn eggs and a few other mod items are whitelisted. This is not 100% guaranteed to work, due to the way everything works.](https://trello.com/c/92C0pp1G/237-you-can-now-whitelist-items-for-spawning-creatures-by-default-spawn-eggs-and-a-few-other-mod-items-are-whitelisted-this-is-not-1)

**Comment by Yuudaari** [comment]
Fixed as of [v4.1.0](https://github.com/Yuudaari/soulus/releases/tag/v4.1.0)
