### ISSUE TITLE
Issue with TOP compat on servers

### ISSUE THREAD

**Issue by pupnewfster** [Yuudaari/soulus#53]
On the server The One Probe just displays:
```
Error: theoneprobe:default
Error: soulus:probe
```
I believe this is because of
https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/compat/top/TheOneProbe.java#L48
and
https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/compat/top/TheOneProbe.java#L83

Those methods you define in IBlock are ClientSide only, however The One Probe is designed to have the servers provide the information, so on a server it is unable to find those methods. There reason there is no error printed out on servers is I believe TOP probably catches any errors and then just displays the above Errors in the probe data.

**Comment by Yuudaari** [comment]
Bahahhahahahahhahahahhaah i hate top

**Comment by pupnewfster** [comment]
I will work on a pull that fixes this, but if you don't mind I probably will also rename a few things rather than just having it all be called waila and remove some excess stuff that is not needed in java 8 (such as having abstract for unimplemented methods in interfaces)

**Comment by Yuudaari** [comment]
Sure, if you feel like it. I initially wasn't going to add TOP support because I hate the mod and the way it does inter-mod support, but I had multiple requests for it. I didn't care enough when adding support to do more than the bare minimum, which is why everything is still named "waila" things. 

Also, please don't do other things besides fixing the TOP support in a single pull. IE: Don't remove abstract from things unrelated to the TOP/Waila support). If there's too many changes it's going to be harder for me to review and I don't have much time as it is.

I can't give a date I'll be able to look at pulls, fyi. I'm very busy with my actual job at the moment and it's only gotten worse from the flu I've had the past couple weeks. And the fact that I have an existing PR I have yet to deal with...

**Comment by pupnewfster** [comment]
Ok, because of those reasons I am also just going to leave method names alone so that it should be very easy to scroll through and see the changes as they were very simple. If needed I can also make a commit that reverts the automatic import reordering so that it is even easier to read.
