### ISSUE TITLE
Add config for whether to show normal recipes in composer tab

### ISSUE THREAD

**Issue by KAfable** [Yuudaari/soulus#57]
Would it be possible to re-implement or add configs so that the Composer doesn't show duplicate 3x3 crafting recipes? 

**Current:**
Composer shows all possible 3x3 recipes, including both duplicates of vanilla 3x3 crafting and the unique recipes for the Composer.

**Proposal**
Re-implement or add configs so that the Composer doesn't show duplicate 3x3 crafting recipes. Can add a JEI tab description instead stating that it is an autocrafter in addition to it's other uses. 

**Why**
Other pack devs have been trying to cut down on clutter in JEI in larger packs, and  having the Composition tab appear twice for nearly every crafting recipe when it really doesn't have additional value-add adds unneeded noise.

Thanks!

**Comment by Yuudaari** [comment]
The reason why I did it this way, I think, was so that you could right click on the composer in JEI in order to see every recipe it could make. But I suppose it doesn't actually help that much to see normal recipes, especially if Soulus is taught to players via a guidebook. I'll add a config option for it and disable the current functionality by default, unless there's some other reason I'm forgetting that made it so this was more important.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [You can now configure whether JEI should display normal crafting recipes in the Composer tab. It's now disabled by default.](https://trello.com/c/jYwNKD7U/263-you-can-now-configure-whether-jei-should-display-normal-crafting-recipes-in-the-composer-tab-its-now-disabled-by-default)
