### ISSUE TITLE
Ex Nihilo Creatio support is broken

### ISSUE THREAD

**Issue by lampyr** [Yuudaari/soulus#67]
hi  i don't see in ex nihilo creatio the config for soulus and in JEI i don't see any bone chunk from the sieve.

Soulus: Soulus-1.12.2-4.1.2-8efec24
Ex nihilo creatio: exnihilocreatio-1.12.2-0.3.8.3
JEI: jei_1.12.2-4.14.4.267

Thank you in advance.

**Comment by Yuudaari** [comment]
Looks like the API was completely changed at some point. I'm not sure how this manages to not crash, to be honest. 

When I initially added Ex Nihilo Creatio support, it was because this mod wasn't any good on its own. At this point, Soulus can stand on its own, so I'm thinking a better path forward is to just remove the sieve drops injection. It's not worth it for me to try to keep up with API changes.

To add them yourself, you can use the Ex Nihilo Creatio JSON recipe system (which doesn't have a guide) or you can use their WIP CraftTweaker integration (which also doesn't have a guide, but it's a bit easier to follow):
https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/compatibility/crafttweaker/Sieve.kt

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The automatically-injected Ex Nihilo Creatio sieve recipes have been removed. If you want to replicate the old functionality, you will need to use Ex Nihilo Creatio's CraftTweaker or JSON recipe support.](https://trello.com/c/vhBMQNfy/313-the-automatically-injected-ex-nihilo-creatio-sieve-recipes-have-been-removed-if-you-want-to-replicate-the-old-functionality-you)
